### ISSUE TITLE
encrypted keyring

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#21]
like the title says, give the user the option to encrypt symmetric keys and private keys so that a password is required for access

**Comment by winhowes** [comment]
How long would access be granted? Per-open popup, Per-browsing session (not sure how that would work off-hand, but I could figure it out), Till they click "log out" (or some derivation)?

**Comment by arnottcr** [comment]
I would say that it should definately be an option, disabled by default as with textsecure. Most gpg implementations allow a user set timeout. But allowing per browser sessions would also be useful.

**Comment by winhowes** [comment]
A problem with this is that the user's password is stored in memory, and if they do some sort of unexpected behavior, there may be a chance that the password could be cleared from memory and it wouldn't be able to encrypt (nothing confirmed here, just speculation). How I've done the basic implementation is you click "Encrypt Keychain" when you want to encrypt, and you enter a password then (allows for changing passwords - otherwise we'll have to build that in) and then whenever you want to decrypt, there's a box for you to enter that password in. Idk what do you think about that approach?

**Comment by arnottcr** [comment]
I have two thoughts, I think I prefer the first:
1) use a key-encryption-key model
  a) startup
    1) generate encryption keyfile
    2) encrypt grd.me default key with keyfile
    2.5) [prompt user to generate new message encryption key, then encrypt with keyfile]
    3) prompt user to either set password or skip [no password]
      a) encrypt keyfile with password [use kdf], prepend with 1 bit, for encrypted
      b) prepend keyfile with 0 bit, for decrypted
    4) write modified keyfile to disk
    5) flush original keyfile from memory
  b) upon new keyshare, new key generation, message encryption or decryption
    1) fetch keyfile from disk
    2) check first bit
    3) if necessary, prompt for password and decrypt
    4) either:
      a) decrypt pertinent key for message decryption or encryption
      b) encrypt new key with keyfile and save new encrypted key to database
    5) flush keyfile from memory
  c) upon password change
    1) with old password
      a) have user enter old password and new password twice
      b) decrypt keyfile on disk
      c) re-encrypt keyfile with new password, save to disk
    2) without old password
    [this will be an expensive operation for large databases, and while we could use the same keyfile instead of generating a new one, it seems like a bad idea to assume that you can securely delete a key that was written to disk; at the same time, this should not be a frequent operation]
      a) generate new keyfile
      b) prompt user for new password
      c) encrypt keyfile with password [use kdf], prepend with 1 bit, for encrypted
      [we need some way to recover from this operation being interrupted, I think have both keys in database till encryption is done is best, and we will need to keep track of what has been processed and not]
      d) read old keyfile into memory
      e) re-encrypt database with new keyfile
2) only encrypt on request
  a) startup
    1) prompt user to set password
      a) if no password [skip]
        1) write 0 bit somewhere to indicate unencrypted
      b) if password
        1) generate keyfile and encrypt with password [use kdf], write to disk
        2) write a 1 bit somewhere to indicate encrypted keyring
        2.5) [prompt user to generate new message encryption key, then encrypt with keyfile]
        3) write encrypted keyfile to disk
        4) flush decrypted keyfile from memory
  b) if not encrypted
    1) upon password change
      a) generate new keyfile
      b) prompt user for new password
      c) encrypt keyfile with password [use kdf], write the 1 bit somewhere, for encrypted
      [we need some way to recover from this operation being interrupted, and we will need to keep track of what has been processed and not]
      e) encrypt database with new keyfile
  c) if encrypted
    1) upon new keyshare, new key generation, message encryption or decryption
      a) fetch keyfile from disk
      c) prompt for password and decrypt
      d) either:
        1) decrypt pertinent key for message decryption or encryption
        2) encrypt new key with keyfile and save new encrypted key to database
      e) flush decrypted keyfile from memory
    2) upon password change
      a) with old password
        1) have user enter old password and new password twice
        2) decrypt keyfile on disk
        3) re-encrypt keyfile with new password, save to disk

**Comment by arnottcr** [comment]
what do you think about the note on 1.c.2)? I think that it is a bad idea to reuse a key that has been written unencrypted to disk, SSDs and all, but that is the one major advantage of 1), if you always have the data encrypted, then you never need to worry about a costly encryption round, also password changes are trivial, no re-encryption necessary

**Comment by winhowes** [comment]
Okay, so a few questions/thoughts:
1. I don't store their password anywhere, so what is the point of asking them to change their password for when they go to encrypt their keychain I must ask for their password then anyways?  Or are you suggesting I store their password in memory somewhere?
2. All those disk read/writes sound expensive. What do you think of my approach below/what are the direct improvements that can happen on top of it?
3. Regarding interrupts - Firefox guarantees "atomic" operations for all of this, so we don't really have to worry about them.
4. I've stored the "flag" bit separately rather than prepending because 
    a. I can fetch that separately rather than fetch the entire encrypted keychain and check
    b. It's just easier through Firefox's and Chrome's sdk

My current approach:
1) startup (installation)
_a) Do nothing - the default key is unencrypted and stored that way.
2) If not encrypted (flag is currently set to 0)
_a) They take no action
__1) store flag of 0 indicating it is not encrypted
_b) They click "Encrypt Keychain"
__1) Prompt for password
__2) Encrypt with password (AES-256 using kdf)
__3) Write encrypted file to disk
__4) Flush unencrypted keychain from memory
__5) Flush password from memory
__6) Store a flag of 1 indicating that it is encrypted
3) If encrypted (flag is currently set to 1)
_a) They take no action
__1) Keychain remains encrypted
__2) Messages cannot be decrypted (password to decrypt keychain is unknown)
__3) Grd Me keyboard shortcuts don't do anything (they can't encrypt)
__4) They are unable to search key server through Grd Me extension
__5) They are unable to add new keys to keychain
__6) Flag remains set to 1
_b) They follow prompt to decrypt keychain
__1) They enter password
__2) Attempt keychain decryption
___a) Failure
____1) Prompt for decryption password
___b) Success
____1) Decrypted keychain written to disk and memory
____2) Encrypted keychain flushed from disk and memory (this operation is atomic with the above)
____3) All features re-enabled
____4) Set flag to 0 indicating keychain is unencrypted

Once they've decrypted the keychain they have to re-encrypt it. To me this model seems to represent the behavior of logging in/logging out except that both actions require a password. A benefit of this is that they can switch their password as much as they like just through this log in/log out process. A downside is that I currently don't require them to confirm their password. Thoughts on this:
1. It is a hassle for the user to write their password twice every time they would like "log out".
2. There is room for typos and thus losing their keychain
3. A possible solution: Store the hash of their most recent password and if the password they enter does not match the hash I ask them to confirm their password. That keeps things hassle-ish free when they're logging out, yet reduces chances of typos causing loss of keychain

**Comment by winhowes** [comment]
I've implemented my possible solution for password confirmation described in my earlier message ^

**Comment by winhowes** [comment]
Added the chrome only tag, as this seems implemented in FF, until I hear otherwise?

**Comment by winhowes** [comment]
I'm gonna go ahead and close this one as the implementation exists. Feel free to reopen if we need to change the implementation.
