### ISSUE TITLE
Add PGP support with OpenPGP.js

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#28]
@floryst  @arnottcr  Do we need to do this? Would this be a good thing to do or would it cause user confusion?

**Comment by arnottcr** [comment]
I think it could be useful, as it would allow greater interoperability; but how do deal with keys will be a bit of a pain. I see two options:
1) allow pgp keys, but keep them separate from all other grdMe keys; as such, you can simply add a check for both ~~grdme~~ and --------Begin PGP Message--------
2) keep all keys together, and since they should be compliant with the underlying crypto system, allow for import of both keys in pgp format and keys in the yet to be designed grdMe format, finally when (de/en)crypting you should be able to use both pgp or grdme keys. Furthermore, you can allow for encrypting of messages in pgp format if that is desired. 
note: both will require a pgp parse routine, which could get really expensive; consider adding a toggle in the settings menu, along with the output format toggle? 

Another thing to consider is that currently you do not support any better security than pgp, only a better UI and integrated key-server. So, best practice in this case is to either integrate with current solutions, so as to not fracture the ecosystem, or create something that brings something new to the table and is better. I like the second, but it is more difficult.

P.S. pfs hijack

**Comment by winhowes** [comment]
Why would pfs prevent us from using pgp? But I would rather have pfs than pgp anyday

**Comment by arnottcr** [comment]
The fear I have for supporting pgp will come with a lot of hassle, from a development perspective, but also has the possibility of confusing users.They need a consistent user interface, and they do not want to worry about what is secure and how the crypto is working. 

I imagine it like keeping your Oxycontin and baby aspirin together in a bottle, most of the time it is nice to not have to worry about which bottle to grab, but it could be hazardous sometimes if you are groggy or not paying attention. And realistically, we would be keeping it around for legacy purposes not because it is good crypto. 

other notes while writing the above:
I see pgp as a much weaker and inferior version of crypto. It was great 10 years ago, but it leaks a lot of metadata and there are issues with it just using one long-term key.

I think pfs is easier for the user: session keys are awesome, you can largely hide key management as the model has changed away from a strong key-server metaphor, also if we can get it working pfs is just a conversation so it could be intuitive [could].

**Comment by winhowes** [comment]
cool, I feel the same way about pgp

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#33
